version: '3.8'

services:
  nestjs:
    build:
      context: . # Thư mục chứa Dockerfile cho NestJS
    container_name: nestjs-backend
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.nestjs.entrypoints=http'
      - 'traefik.http.routers.nestjs.rule=PathPrefix(`/api`) && Host(`traefik.tinhtisonen.com`)'
      - 'traefik.http.routers.nestjs-secure.entrypoints=https'
      - 'traefik.http.routers.nestjs-secure.rule=PathPrefix(`/api`) && Host(`traefik.tinhtisonen.com`)'
      - 'traefik.http.routers.nestjs-secure.tls.certresolver=letsencrypt'
  
    networks:
      - traefik  # Kết nối container NestJS với network traefik


networks:
  traefik:
    external: true  # Đảm bảo Traefik và các dịch vụ container sử dụng cùng network này


